spring:
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    host: localhost
    port: 6379
app:
  topic:
    wordcount: wordcount
  data_keys:
    word_counts: word_counts
    top_10_words: top_10_words
